### PR TITLE
Readd Attention Please

### PR DESCRIPTION
**Pull request by garantiertnicht**
It was in the wrong path

### CODE REVIEW

**Comment by garantiertnicht** [comment]
WIP

**Comment by ICTman1076** [comment]
bruh moment

**Comment by ICTman1076** [comment]
The rest of yo body is emoji restrictor, is this intended behaviour?

**Comment by ICTman1076** [comment]
wait wait wait I'm confused now

**Comment by ICTman1076** [comment]
I think u mixed the two files up with 1b84866

**Comment by garantiertnicht** [comment]
No, the header was wong and was fixed in the second commit

**Comment by ICTman1076** [comment]
yea but I think u made it more wrong lmao https://img.ictman.tk/RSRougu3

**Comment by garantiertnicht** [comment]
Ifyou want to do something well, you better use the cli. Should be fine now

**Comment by ICTman1076** [comment]
lmao ok all is well now

**Pull request merged**
