### PR TITLE
Add PING PONG BOT

### PR DESCRIPTION
**Pull request by CODE-COMMANDERx**
HELLO PERSON ADDING YOUR BOT! PLEASE CHECK ALL THESE THINGS BY ADDING A * IN THE BRACKETS OR GITHUB WILL BE ANGRY AT YOU:

# My Pull Request definitely has
- [x] One or more bots in the bots folder
- [x] An invite for each bot
- [x] A title that is my bot's name
- [x] A description that describes my bot

PUT ANYTHING ELSE BELOW HERE MATE:

### CODE REVIEW

**Comment by ICTman1076** [comment]
Please check the boxes in your PR's body

**Comment by CODE-COMMANDERx** [comment]
Done!

**Comment by ICTman1076** [comment]
Your bot is a simple ping test bot. It does not need admin permissions.
Also, I'd appreciate it if you didn't use bitly links for your invite.
Also, your bot's offline anyway.
Also, you didn't check the first box.

*This PR will NOT be merged until these are fixed. If not fixed within 7 days, I will close this PR. If you do fix it, please check this box*
- [ ] I have resolved all issues mentioned.

**Comment by ICTman1076** [comment]
Ok I'll close this if you're not going to make these kinda simple fixes. IDC if your bot's offline, but I do care about the rest

**Comment by ICTman1076** [comment]
Dead PR, bot owner refuses to make simple fixes

**Pull request closed without merging**
